### ISSUE TITLE
DeprecationWarning with node v8.9.3 in history.js line 68

### ISSUE THREAD

**Issue by pusateri** [adaltas/node-shell#18]
```
node --throw-deprecation index.js
Type "help" or press enter for a list of commands
(nst) help
Available commands:
quit                Exit this shell
help                Show this message
(nst) quitInternal error, closing...
Calling an asynchronous function without callback is deprecated.
DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    at maybeCallback (fs.js:119:42)
    at Object.fs.write (fs.js:692:16)
    at Interface._addHistory (/Users/pusateri/Projects/nst/node_modules/shell/lib/plugins/history.js:68:12)
    at Interface._line (readline.js:629:19)
    at Interface._ttyWrite (readline.js:911:14)
    at ReadStream.onkeypress (readline.js:160:10)
    at emitTwo (events.js:126:13)
    at ReadStream.emit (events.js:214:7)
    at emitKeys (internal/readline.js:420:14)
    at emitKeys.next (<anonymous>)

```

**Comment by wdavidw** [comment]
Thank you

**Comment by wf9a5m75** [comment]
This error still occurs in v0.5.0

```
const shell = require('shell');

const app = new shell();

app.cmd('test', 'hello question', (req, res, next) => {
  console.log('hello world');
  next();
});

```

```
Type "help" or press enter for a list of commands
>> test
hello world
>> (node:33929) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```
